export const ADD_ENTRY = 'ADD_ENTRY';
export const INIT_ENTRIES = 'INIT_ENTRIES';
export const REMOVE_ENTRY = 'REMOVE_ENTRY';
export const REMOVE_ALL_ENTRIES = 'REMOVE_ALL_ENTRIES';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const UPDATE_FORM = 'UPDATE_FORM';
export const TOGGLE_REQUIREMENTS = 'TOGGLE_REQUIREMENTS';
export const DELETE_TOAST = 'DELETE_TOAST';